
version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  backend:
    env_file:
      "./backend/backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
  